name: build
on: { workflow_dispatch, push }
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        system: [{ os: Linux, arch: X64 }, { os: macOS, arch: ARM64 }]
    name: "${{ matrix.system.os }} ${{ matrix.system.arch }}"
    runs-on: [nix, "${{ matrix.system.os }}", "${{ matrix.system.arch }}"]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V28
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= benaduggan.cachix.org-1:BY2tmi++VqJD6My4kB/dXGfxT7nJqrOtRVNn9UhgrHE= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw= jacobi.cachix.org-1:JJghCz+ZD2hc9BHO94myjCzf4wS3DeBLKHOz3jCukMU= kwbauson.cachix.org-1:a6RuFyeJKSShV8LAUw3Jx8z48luiCU755DkweAAkwX0=
            substituters = https://cache.nixos.org/ https://benaduggan.cachix.org https://devenv.cachix.org https://jacobi.cachix.org https://kwbauson.cachix.org
      - run: nix -L --show-trace build
      # figure this out in the future
      # - run: nix -L build .#checks.default
      # - run: ./result/bin/checks
      - name: "cachix only on main and updates-all branches"
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/updates-all'
        run: |
          cachix authtoken '${{ secrets.CACHIX_AUTH_TOKEN }}'
          cachix push benaduggan ./result
