name: Check for updates
on: { workflow_dispatch, schedule: [cron: "0 7 * * *"] }
jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix -vL run .#nle update
      - uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          delete-branch: true
          title: Automatic update
          commit-message: Automatic update
          branch: automatic-update
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: gh pr merge --auto --squash ${{ steps.cpr.outputs.pull-request-url }}
