name: checks
on: { workflow_dispatch, push }
jobs:
  statix:
    runs-on: [nix, Linux, X64]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - run: nix run .#statix -- check
  deadnix:
    runs-on: [nix, Linux, X64]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - run: nix run .#deadnix -- -f .
  prettier:
    runs-on: [nix, Linux, X64]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - run: nix run .#nodePackages.prettier -- --check .
  nixpkgs-fmt:
    runs-on: [nix, Linux, X64]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - run: nix run .#nixpkgs-fmt -- --check .
