name: checks
on: { workflow_dispatch, push }
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12]
    name: build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - run: nix -L --show-trace build
      - name: "cachix only on main"
        if: github.ref == 'refs/heads/main'
        run: |
          cachix authtoken '${{ secrets.CACHIX_AUTH_TOKEN }}'
          cachix push benaduggan ./result
          cd ./result/builds
          for build in *;do
            cachix pin benaduggan $GITHUB_SHA-$build $(realpath $build) --keep-days 3
          done

  statix:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - run: nix run .#statix -- check
  deadnix:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - run: nix run .#deadnix -- -f .
  prettier:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - run: nix run .#nodePackages.prettier -- --check .
  nixpkgs-fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - run: nix run .#nixpkgs-fmt -- --check .
